### PR TITLE
Can return backdrops for movie

### PR DESCRIPTION
**Pull request by yozzz**
Change previous class `Grabber` to `PosterGrabber`, add class `BackdropGrabber` that returns backgrounds for movie, add in module `can_haz_poster` self method `grab_backdrop` wich will call class method and return the backdrops for movie also add integration test on class `BackdropGrabber` and fixtures for it

<% CanHazPoster.grab_backdrop('The Matrix', 1999).each do |bg| %>
  <%= bg %>
<% end %>

### CODE REVIEW

**Comment by yozzz** [comment]
Emmm, I have no idea :)

**Comment by RKushnir** [comment]
Are you sure it's `proejct`, and not `project` ?

**Comment by yozzz** [comment]
Ouu, now see it :(

**Comment by yozzz** [comment]
If somebody will ask me what is backdrop, I will not know what to say, I will say this like background :)

**Comment by yozzz** [comment]
Maybe we should also change module name CanHazPoster just to CanHaz?

**Comment by RKushnir** [comment]
> If somebody will ask me what is backdrop, I will not know what to say, I will say this like background :)

And if somebody asks me what is background, movies will be the last thing I think of :) Backdrop looks like a specialized term, so "movie background fans" should be aware of it.

> Maybe we should also change module name CanHazPoster just to CanHaz?

I don't think it's a good idea because `can_haz` doesn't tell anything about what the gem does.

**Comment by RKushnir** [comment]
Hey,
sorry for the delay, I didn't get the notification. Looks like everything's fine, just squash the commits into one, so I can see all the changes in one place.

**Comment by yozzz** [comment]
That was bad squash :( 
Think I should close it pr

**Pull request closed without merging**
